flask/blueprints/locations.py
import os
import pymongo
from flask import Blueprint, render_template, abort, flash, session, redirect, url_for, request, jsonify
from pymongo import MongoClient
from bson.objectid import ObjectId

location_bp = Blueprint("location", __name__, template_folder='templates')

mongo_uri = os.environ.get("MONGO_URI")
if not mongo_uri:
    raise ValueError("No MONGO_URI environment variable set")
client = MongoClient(mongo_uri)
db = client["carrentalmanagement"]
locations_collection = db["central"]

class location_template:
    def __init__(self, name, zipcode, region, streetname, location, rent):
        self.name = name
        self.zipcode = zipcode
        self.region = region
        self.streetname = streetname
        self.location = location
        self.rent = rent

@location_bp.route("/locations")
def list_location():
    if 'username' not in session:
        flash('Please log in to access this page.', 'error')
        return redirect(url_for('login.login'))
    documents = get_updated_locations()
    show_navbar = True
    return render_template("locationview.html", show_navbar = show_navbar, data=documents)

@location_bp.route("/locations", methods=["GET", "POST"])
def filter_location():
    if 'username' not in session:
        flash('Please log in to access this page.', 'error')
        return redirect(url_for('login.login'))

    search_input = request.form.get('search-input')
    search_category = request.form.get('search-category')
    filtered_locations = get_filtered_locations(search_input, search_category)
    show_navbar = True
    if search_category or search_input:
        return render_template("locationview.html", show_navbar = show_navbar, data=filtered_locations, search_input=search_input, search_category=search_category)
    return render_template("locationview.html", show_navbar = show_navbar, data=filtered_locations)

@location_bp.route('/edit/<location_id>', methods=['GET', 'POST'])
def edit_location(location_id):
    if request.method == 'POST':
        filter_criteria = {'_id': ObjectId(location_id)}
        retrived_location = location_template(request.form.get('name'),
                                              request.form.get('zipcode'),
                                              request.form.get('region'),
                                              request.form.get('streetname'),
                                              request.form.get('location'),
                                              request.form.get('rent'))
        update_criteria = {
            "$set": {
                "name": retrived_location.name,
                "zipcode": retrived_location.zipcode,
                "region": retrived_location.region,
                "streetname": retrived_location.streetname,
                "location": retrived_location.location,
                "rent": retrived_location.rent
            }
        }
        update_response = locations_collection.update_one(filter_criteria, update_criteria)
        show_navbar = True
        try:
            if update_response.matched_count > 0:
                if update_response.modified_count > 0:
                    flash("Location updated successfully!", "success")
                else:
                    flash("No changes detected in location data.", "warning")
            else:
                alert_type = "error"
                alert_String = "Location with ID " + location_id + " not found."
        except pymongo.errors.PyMongoError as e:
            alert_type = "error"
            alert_String = "An error occurred while updating the location: " + e

        #updated_documents = get_updated_locations()
        return redirect(url_for('location.list_location'))

@location_bp.route('/add', methods=['GET', 'POST'])
def add_location():
    if request.method == 'POST':
        location_data = {
            "name": request.form.get('name'),
            "zipcode": request.form.get('zipcode'),
            "region": request.form.get('region'),
            "streetname": request.form.get('streetname'),
            "location": request.form.get('location'),
            "rent": request.form.get('rent')
        }

        added_response = locations_collection.insert_one(location_data)
        show_navbar = True
        try:
            if added_response.acknowledged:
                flash("Location added successfully!", "success")
            else:
                flash("Could not add the location. Please try again.", "warning")

        except pymongo.errors.PyMongoError as e:
            print(e)

        return redirect(url_for('location.list_location'))

@location_bp.route('/delete', methods=['POST'])
def delete_locations():
    selected_locations = request.form.get('selected-locations')

    if selected_locations:
        location_ids = [ObjectId(id.strip()) for id in selected_locations.split(',')]
        selected_docs = locations_collection.find({"_id": {"$in": location_ids}})
        location_names = [doc['name'] for doc in selected_docs]
        
        flash(f'Selected locations: {location_names}', 'info')
        try:
            delete_response = locations_collection.delete_many({"_id": {"$in": location_ids}})
            if delete_response.deleted_count > 0:
                flash("Location(s) deleted successfully!", "success")
            else:
                flash("Couldn't delete the location(s). Please try again.", "error")
        except pymongo.errors.PyMongoError as e:
            flash(f"An error occurred while deleting locations: {str(e)}", "error")
    else:
        flash("No locations selected for deletion.", "error")

    return redirect(url_for('location.list_location'))

def get_updated_locations():
    updated_locations = locations_collection.find().sort("name")
    data = []
    for location in updated_locations:
        location["employees"] = len(location.get("employees", []))
        location["vehicles"] = len(location.get("vehicles", []))
        data.append(location)
    return data

def get_filtered_locations(search_input, search_category):
    updated_locations = locations_collection.find({search_category: {"$regex": search_input, "$options": "i"}}).sort("name")
    data = []
    for location in updated_locations:
        location["employees"] = len(location.get("employees", []))
        location["vehicles"] = len(location.get("vehicles", []))
        data.append(location)
    return data

flask/blueprints/login.py
import os
import bcrypt
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from pymongo import MongoClient

login_bp = Blueprint('login', __name__, template_folder='templates')

mongo_uri = os.environ.get("MONGO_URI")
if not mongo_uri:
    raise ValueError("No MONGO_URI environment variable set")
client = MongoClient(mongo_uri)
db = client["carrentalmanagement"]
users_collection = db["sys_admins"]

@login_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = users_collection.find_one({"email": email})
        if user and bcrypt.checkpw(password.encode('utf-8'), user['password'].encode('utf-8')):
            session['username'] = user['username']
            flash('Login successful!', 'success')
            return redirect(url_for('location.list_location'))
        else:
            flash('Invalid email or password', 'danger')
            return redirect(url_for('login.login'))

    return render_template('loginview.html')

@login_bp.route('/logout')
def logout():
    session.pop('username', None)
    flash('You have been logged out.', 'success')
    return redirect(url_for('index'))



flask/blueprints/performance.py
import os
from datetime import datetime, date
from turtle import pd

import numpy as np
from flask import current_app, request
from flask import Blueprint, render_template, abort, flash, session, redirect, url_for, Response
from matplotlib import pyplot as plt
from pymongo import MongoClient
from weasyprint import HTML

performance_bp = Blueprint("performance", __name__, template_folder='../../templates')

mongo_uri = os.environ.get("MONGO_URI")
if not mongo_uri:
  raise ValueError("No MONGO_URI environment variable set")
client = MongoClient(mongo_uri)
db = client["carrentalmanagement"]
locations_collection = db["central"]
vehicles_collection = db["vehicle"]
vehicle_costs_collection = db["vehicle_costs"]
rental_agreements_collection = db["rentalagreement"]
performance_data_collection = db["keydata"]
employee_collection = db["employee"]

locations = list(locations_collection.find({}))
vehicles = list(vehicles_collection.find({}))
vehicle_costs = list(vehicle_costs_collection.find({}))
rental_agreements = list(rental_agreements_collection.find({}))
performance_data = list(performance_data_collection.find({}))
employees = list(employee_collection.find({}))

default_file_path = 'static/diagrams/'

@performance_bp.route("/performance")
def prev_performance():
  if 'username' not in session:
    flash('Please log in to access this page.', 'error')
    return redirect(url_for('login.login'))
  else:
    vtype_usage_filename = gen_Car_usage_pie_chart()
    revenue_quater_filename = gen_coast_comp_bar_chart()
   # car_availabitlity_filename = gen_car_availability_chart()

      # Render the template with the image path
    show_navbar = True
    show_toolbar = True
    return render_template('performanceview.html', show_navbar=show_navbar, show_toolbar=show_toolbar)


@performance_bp.route("/performance/pdf", methods=['GET', 'POST'])
def print_performance_pdf():
    if 'username' not in session:
        flash('Please log in to access this page.', 'error')
        return redirect(url_for('login.login'))
    else:
      if request.method == 'POST':
        current_date = date.today()
        filename = "Bericht-"
        res_filename = request.form.get('pdf_filename')
        if(len(res_filename) != 0):
          if(res_filename.endswith('-')):
            filename = res_filename
          else:
            filename = res_filename + "-"

        filename = filename + current_date.strftime("%d-%M-%Y") + ".pdf"

        # Render HTML content
        html_content = render_template("performanceview.html", show_tooltips=False)

        # Generate PDF using WeasyPrint
        pdf = HTML(string=html_content, base_url=url_for('static', filename=filename, _external=True)).write_pdf()

        # Optionally, you can save the PDF to a file
        # with open('output.pdf', 'wb') as f:
        #     f.write(pdf)

        # Return PDF as a response
        response = Response(pdf, mimetype='application/pdf')
        response.headers['Content-Disposition'] = f"attachment; filename={filename}"
        return response
      else:
        return None


# minions

def gen_Car_usage_pie_chart():
  filename = f"{default_file_path}/type_usage_pie_chart.png"
  pkw_usage = 0
  lkw_usage = 0
  transport_usage = 0
  if(len(rental_agreements) >= 0 &  len(vehicles) >= 0):
    for rental_agreement in rental_agreements:
      for vehicle in vehicles:
        if vehicle.get('_id') == rental_agreement.get('vehicles'):
          if vehicle.get('vehicletype') == 'PKW':
            pkw_usage += 1
          elif vehicle.get('vehicletype') == 'LKW':
            lkw_usage += 1
          elif vehicle.get('vehicletype') == 'Transporter':
            transport_usage += 1

    # make data
    max = lkw_usage + pkw_usage + transport_usage
    pkw_percent = (pkw_usage / max) * 100
    lkw_percent = (lkw_usage / max) * 100
    transport_percent = (transport_usage / max) * 100

    labels = 'PKW', 'LKW', 'Transport'
    x_data = [pkw_percent, lkw_percent, transport_percent]

    # plot
    plt.rcParams['figure.facecolor'] = '#222222'
    fig, ax = plt.subplots()
    colors=['darkviolet', 'blueviolet', 'slateblue', 'darkslateblue']
    ax.pie(x_data,
           labels=labels,
           autopct='%1.1f%%',
           colors=colors,
           shadow={'ox': -0.04, 'edgecolor': 'none', 'shade': 0.9},
           pctdistance=.3,
           labeldistance=.6)
    plt.title('Nutzungsverteilung der verschiedenen Fahrzeugtypen', color='white')
    plt.tight_layout

    # Save the plot as an image
    plt.savefig(filename)
    plt.close()  # Close the plot to avoid memory issues
    return filename
  else:
    current_app.logger.debug(f"Collections {rental_agreements} or {vehicles_collection} is empty.")
    return False

def gen_coast_comp_bar_chart():
  filename = f"{default_file_path}/revenue_quater.png"
  # make data
  quarters = ()
  values_per_quater = {
    'Einnahmen': (),
    'zukünftige_Einnahmen': (),
    'Ausgaben' : ()}
  # adding past data
  if(len(performance_data) >=0):
    for performance_set in performance_data:
      if performance_set['year'] == date.today().year:
        quarters = quarters + (performance_set.get('quater'),)

        revenue = performance_set.get('revenue', 0.00)  # Default to 0 for missing 'revenue'
        cost = performance_set.get('cost', 0.00)  # Default to 0 for missing 'personal_costs'
        outstanding_revenue = 0.00

        values_per_quater['Einnahmen'] = values_per_quater['Einnahmen'] + (float(revenue),)
        values_per_quater['zukünftige_Einnahmen'] = values_per_quater['zukünftige_Einnahmen'] + (float(outstanding_revenue),)
        values_per_quater['Ausgaben'] =  values_per_quater['Ausgaben'] + (float(cost),)

  # adding current data (current revenue, current outstanding revenue and current cost)
  date_format = '%d.%m.%Y'
  current_date = date.today()
  current_quarter_timespan = get_start_of_quarter(current_date)

  current_app.logger.debug(f"current_date {current_date}")
  current_app.logger.debug(f"quaters:  {current_quarter_timespan}")

  rental_agreements_past_date = list()
  rental_agreements_pre_date = list()

  for rental_agreement in rental_agreements:
    receives_date = datetime.strptime(rental_agreement.get('receives', 0), date_format).date()
    return_date = datetime.strptime(rental_agreement.get('returned', 0), date_format).date()
    if(return_date != 0 and receives_date != 0):
      if(receives_date >= current_quarter_timespan.get('start_date') and return_date <= current_quarter_timespan.get('end_date')):
        if(current_date > return_date):
          current_app.logger.debug("added to rental_agreement_pre_date")
          rental_agreements_pre_date.append(rental_agreement)
        elif(current_date < receives_date):
          current_app.logger.debug("added to rental_agreement_past_date")
          rental_agreements_past_date.append(rental_agreement)

  current_app.logger.debug(f"rental_agreements_pre_date: {len(rental_agreements_pre_date)} rental_agreements_past_date: {len(rental_agreements_past_date)}")

  current_revenue = 0.00
  current_cost = 0.00
  current_outstanding_revenue = 0.00

  for rental_agreement_pre in rental_agreements_pre_date:
    for vehicle in vehicles:
      if rental_agreement_pre.get('vehicles') == vehicle.get('_id'):
        # revenue
        cost_per_day = vehicle.get('cost_per_day')
        rental_time = days_between(rental_agreement_pre.get('receives'), rental_agreement_pre.get('returned'))
        current_revenue += cost_per_day * rental_time

  for rental_agreement_past in rental_agreements_past_date:
    for vehicle in vehicles:
      # revenue
      if rental_agreement_past.get('vehicles') == vehicle.get('_id'):
        cost_per_day = vehicle.get('cost_per_day')
        rental_time = days_between(rental_agreement_past.get('receives'), rental_agreement_past.get('returned'))
        current_outstanding_revenue += cost_per_day * rental_time

  for vehicle_cost in vehicle_costs:
    cost_date = datetime.strptime(vehicle_cost.get('date', 0), date_format).date()
    if current_quarter_timespan.get('start_date') <= cost_date <= current_quarter_timespan.get('end_date'):
      current_cost += vehicle_cost.get('costs')

  for employee in employees:
    current_cost += employee.get('monthly_wage') * 3

  current_app.logger.debug(f"Collection: {values_per_quater}")
  current_app.logger.debug(f"current_revenue -> {current_revenue}")
  current_app.logger.debug(f"current_outstanding_revenue -> {current_outstanding_revenue}")
  current_app.logger.debug(f"current_cost -> {current_cost}")

  quarters += ("current",)
  values_per_quater['Einnahmen'] = values_per_quater['Einnahmen'] + (float(current_revenue),)
  values_per_quater['zukünftige_Einnahmen'] = values_per_quater['zukünftige_Einnahmen'] + (float(current_outstanding_revenue),)
  values_per_quater['Ausgaben'] = values_per_quater['Ausgaben'] + (float(current_cost),)
  y_height = max(max(values_per_quater[category]) for category in values_per_quater) + 100000

  current_app.logger.debug(f"values_per_quater: {values_per_quater}")

  # create graph
  x = np.arange(len(quarters))  # the label locations
  width = 0.25  # the width of the bars
  multiplier = 0

  plt.rcParams['figure.facecolor'] = '#222222'
  fig, ax = plt.subplots(layout='constrained')

  for attribute, measurement in values_per_quater.items():
    offset = width * multiplier
    rects = ax.bar(x + offset, measurement, width, label=attribute)
    ax.bar_label(rects, padding=3, color='white')
    multiplier += 1

  ax.tick_params(axis='x', colors='white')
  ax.tick_params(axis='y', colors='white')
  ax.set_facecolor('#222222')

  ax.set_ylabel('Euro (€)', color='white')
  ax.set_title('Gewinn und Verlustrechnung' , color='white')
  ax.set_xticks(x + width, quarters, color='white')
  ax.legend(loc='upper left', ncols=3, facecolor='#222222', labelcolor='white')
  ax.set_ylim(0, y_height)

  plt.savefig(filename)
  plt.close()

def gen_car_availability_chart():

flask/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{{ url_for('static', filename='css/bootstrap/bootstrap.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block head %}{% endblock %}
  </head>
  <body class="fade-in">
    <div class="d-flex flex-column min-vh-100 min-vw-100">
      {% if show_navbar is defined and show_navbar %}
        <div class="header container-fluid">
          <nav class="navbar navbar-expand-lg navbar-custom rounded">
            <div class="container">
              <a class="navbar-brand" href="#">
                <img src=static/pics/car-rental-company2.svg alt="Logo" style="width: 50px; height: auto;">
              </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link {% if request.endpoint == 'location.list_location' %}active{% endif %}" href="{{ url_for('location.list_location')}}">Mietstationverwaltung</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link {% if request.endpoint == 'management.list_management' %}active{% endif %}" href="{{ url_for('management.list_management')}}">Personalverwaltung</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link {% if request.endpoint == 'vehicles.list_vehicles' %}active{% endif %}" href="{{ url_for('vehicles.list_vehicles')}}">Fahrzeugverwaltung</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link {% if request.endpoint == 'performance.prev_performance' %}active{% endif %}" href="{{ url_for('performance.prev_performance')}}">Performanceberichte</a>
                  </li>
                </ul>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                  {% if 'username' in session %}
                    <li class="nav-item">
                      <a class="nav-link" href="#">{{ session['username'] }}</a>
                    </li>
                    <li class="nav-item-logout">
                      <a class="nav-link" href="{{ url_for('login.logout') }}">Logout</a>
                    </li>
                  {% else %}
                    <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('login.login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('register.register') }}">Register</a>
                    </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </nav>
        </div>
      {% endif %}
      <div class="container mt-3">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            <div id="flash-messages">
              {% for category, message in messages %}
                <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                  {{ message }}
                </div>
              {% endfor %}
            </div>
          {% endif %}
        {% endwith %}
      </div>
      <div class="container rounded my-20 d-inline-flex justify-content-center primary_accent_color fade-in">
        {% block body %}{% endblock %}
      </div>
    </div>
    <script>
      // Hide flash messages after 5 seconds
      setTimeout(function() {
          $('#flash-messages .alert').alert('close');
      }, 5000);
    </script>
  </body>
</html>

flask/templates/error404view.html
{# This simple template derives from ``base.html``. See ``base.html`` for
   more information about template inheritance. #}
   {%- extends "base.html" %}

   {% block head%} 
        
   {% endblock %}

   {% block body%} 
        I landed on the error 404 page
   {% endblock %}

flask/templates/error500view.html
{# This simple template derives from ``base.html``. See ``base.html`` for
   more information about template inheritance. #}
   {%- extends "base.html" %}

   {% block head%} 
        
   {% endblock %}

   {% block body%} 
        I landed on the error 500 page
   {% endblock %}

flask/templates/index.html
{# This simple template derives from ``base.html``. See ``base.html`` for
   more information about template inheritance. #}
   {%- extends "base.html" %}

   {% block head%} 
        <title> Im a Title </title>
   {% endblock %}

   {% block body%} 
    
   {% endblock %}

flask/templates/loginview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="{{ url_for('static', filename='css/bootstrap/bootstrap.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/loginview.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container mt-3">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                        {{ message }}
                    </div>
                    <script>
                        // Automatically close and fade out the alert after 5 seconds
                        const alertElement = document.querySelector('.alert');
                        setTimeout(function() {
                            alertElement.classList.add('fade');
                            alertElement.style.transition = 'opacity 2s ease-out';
                            alertElement.style.opacity = '0';
                            setTimeout(function() {
                                alertElement.remove();
                            }, 2000); // Remove after fade out transition completes (1s)
                        }, 5000); // 5000 milliseconds (5 seconds)
                    </script>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>

    <div class="d-flex justify-content-center align-items-center vh-100">
        <div class="card text-white shadow-lg" style="width: 100%; max-width: 400px;">
            <div class="card-body p-4">
                <div class="heading-box">
                    <h2 class="card-title text-white">Login</h2>
                </div>
                <form method="POST" action="{{ url_for('login.login') }}">
                    <div class="form-group mb-3">
                        <label for="email" class="form-label text-white">E-Mail</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="password" class="form-label text-white">Passwort</label>
                        <input type="password" class="form-control" id="password" name="password" required>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Login</button>
                </form>
                <div class="text-center mt-3">
                    <p class="text-white">Noch keinen Account? <a href="{{ url_for('register.register') }}" class="text-decoration-none" style="color: var(--primary-accent-color);">Hier Registrieren</a></p>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

flask/templates/performanceview.html
{% extends "base.html" %}

{% block title %}Performance-Berichte{% endblock %}
{% block head%}
<link href="{{ url_for('static', filename='css/performance.css') }}" rel="stylesheet">
{% endblock %}

{% block body%}
    <div class="container-fluid d-grid align-items-center">
        {% if show_toolbar is defined and show_toolbar %}
        <div class="container-fluid text-end row gap-3 pt-3 ">
            <form id="print-form" method="post" action="{{ url_for('performance.print_performance_pdf') }}">
                <input type="search" class="textfield rounded secondary_background-color" id="pdf_filename" name="pdf_filename" placeholder="Filename ... " autofocus>
                <button type="submit" class="btn btn-danger" id="remove-button">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                        <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                    </svg> Drucken
                </button>
            </form>
        </div>
        {% endif %}
        <div class="container align-content-center text-center">
            <div class="row chart-page">
                <h1>Car rental example Performance Preview</h1>
            </div>
            <div class="row charts">
                <img  class="rounded-5 row charts" src="{{ url_for('static', filename='diagrams/type_usage_pie_chart.png') }}" alt="Usage Pie chart">
                <div class="">
                    <h2 class="row">Nutzungsverteilung der verschiedenen Fahrzeugtypen in laufenden oder vergangenden Mietverträgen</h2>
                    <h3 class="row"> Abgebildet ist ein Kuchendiagramm, dass die prozentuale Nutzungsverteilung der verschieden angebotenen Fahrzeugtypen darstellt. Die genutzten Daten beziehen sich auf alle Mietverträge aus dem derzeitigen Jahr.</h3>
                </div>
            </div>
            <div class="row charts" style="break-before: page">
                <img  class="rounded-5 row charts" src="{{ url_for('static', filename='diagrams/revenue_quater.png') }}" alt="Usage Pie chart">
                <div class="">
                    <h2 class="row">Einfache Kosten- und verlustrechnung für das derzeitige und rückwirkende Quartal</h2>
                    <h3 class="row">Abgebildet sind alle Kosten und Einnahmen von allen zurückwirkend Quarteln. Für das derzeitige werden alle noch anstehenden Einnahmen als potenzielle Einnahmen angegeben.</h3>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Einbindung von Chart.js und deinem charts.js -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="{{ url_for('static', filename='js/charts.js') }}"></script>
<script>
    // Ruft die Daten ab und ruft die Funktion zum Rendern der Diagramme auf
    fetch('/performance_reports')
        .then(response => response.json())
        .then(data => renderCharts(data))
        .catch(error => console.error('Fehler beim Laden der Daten:', error));
</script>
{% endblock %}

flask/templates/template.html
{# This simple template derives from ``base.html``. See ``base.html`` for
   more information about template inheritance. #}
   {%- extends "base.html" %}

   {% block head%} 
        <title> Im a Title </title>
        
   {% endblock %}

   {% block body%} 
    
   {% endblock %}